(ns clad.views.questions)

(def qs
  (array-map
   "Sector"
   {:question "Please indicate your sector of interest.."
    :responses ["Not sector specific"
                "Planning, including Spatial and Sustainable Development"
                "Agriculture & Horticulture"
                "Biodiversity & Nature Conservation"
                "Emergency planning and Services"
                "Energy"
                "Financial Services and Insurance"
                "Fisheries"
                "Flood Management and Coastal issues"
                "Forestry"
                "Health"
                "Leisure"
                "Tourism & Lifestyle"
                "Manufacturing & Industry"
                "Retail"
                "Services"]}
   "Satisfaction"
   {:question "How satisfied were you overall with your experience on the site?"
    :responses ["Very dissatisfied"
                "Dissatisfied"
                "Unsure"
                "Satisfied"
                "Very satisfied"]}
   "Navigation"
   {:question "How easy was it to navigate within the website?"
    :responses ["Very difficult"
                "Difficult"
                "Neutral"
                "Easy"
                "Very easy"]}
   "Organisation"
   {:question "How well was the information organised within the site?"
    :responses ["Very disorganised"
                "Disorganised"
                "Unsure"
                "Well organised"
                "Very well organised"]}
   "Quality"
   {:question "How was the overall quality of the website content?"
    :responses ["Poor"
                "Fair"
                "Good"
                "Very good"
                "Excellent"]}
   "Layout"
   {:question "How was the layout and design of the website?"
    :responses ["Poor"
                "Fair"
                "Good"
                "Very good"
                "Excellent"]}
   "Usefulness"
   {:question "How useful was the website content to you?"
    :responses ["Not at all useful"
                "Slightly useful"
                "Somewhat useful"
                "Moderately useful"
                "Extremely useful"]}
   "Adaptation"
   {:question "How useful was the section on Adaptation Information to you?"
    :responses ["Not at all useful"
                "Slightly useful"
                "Somewhat useful"
                "Moderately useful"
                "Extremely useful"]}
   "ClimateChange"
   {:question "How useful was the section on Climate Change to you?"
    :responses ["Not at all useful"
                "Slightly useful"
                "Somewhat useful"
                "Moderately useful"
                "Extremely useful"]}
   "ClimateInformation"
   {:question "How useful was the section on Climate Information and data to you?"
    :responses ["Not at all useful"
                "Slightly useful"
                "Somewhat useful"
                "Moderately useful"
                "Extremely useful"]}
   "SectoralInformation"
   {:question "How useful was the section on Sectoral Information to you?"
    :responses ["Not at all useful"
                "Slightly useful"
                "Somewhat useful"
                "Moderately useful"
                "Extremely useful"]}
   "Reason"
   {:question "Please indicate your primary reason for visiting Climate Ireland"
    :responses ["To learn about Adaptation"
                "To learn about Climate Change"
                "To examine Climatic Information and Data"
                "For guidance on developing an adaptation plan"]
    :freetext "Other"}
   "Find"
   {:question "If you were looking for information how easily were you able to find it?"
    :responses ["Very difficult"
                "Difficult"
                "Neutral"
                "Easily"
                "Very easily"]
    :freetext "Comment"}
   "Understand"
   {:question "Was the information provided clear and easy and to understand?"
    :responses ["Very difficult"
                "Difficult"
                "Neutral"
                "Easy"
                "Very easy"]
    :freetext "Comment"}))
  
