(ns clad.views.questions)

(def qs
  {"Sector"
   {:question "Please indicate your sector of interest.."
    :responses ["Not sector specific"
                "Planning, including Spatial and Sustainable Development"
                "Agriculture & Horticulture"
                "Biodiversity & Nature Conservation"
                "Emergency planning and Services"
                "Energy"
                "Financial Services and Insurance"
                "Fisheries"
                "Flood Management and Coastal issues"
                "Forestry"
                "Health"
                "Leisure"
                "Tourism & Lifestyle"
                "Manufacturing & Industry"
                "Retail"
                "Services"]}
   "Satisfaction"
   {:question "How satisfied were you overall with your experience on the site?"
    :responses ["Very dissatisfied"
                "Dissatisfied"
                "Unsure"
                "Satisfied"
                "Very satisfied"]}
   "Navigation"
   {:question "How easy was it to navigate within the website?"
    :responses ["Very difficult"
                "Difficult"
                "Neutral"
                "Easy"
                "Very easy"]}
   "Organisation"
   {:question "How well was the information organised within the site?"
    :responses ["Very disorganised"
                "Disorganised"
                "Unsure"
                "Well organised"
                "Very well organised"]}
   "Quality"
   {:question "How was the overall quality of the website content?"
    :responses ["Poor"
                "Fair"
                "Good"
                "Very good"
                "Excellent"]}
   "Adaptation"
   {:question "How useful was the section on climate adaptation to you?"
    :responses ["Not at all useful"
                "Slightly useful"
                "Somewhat useful"
                "Moderately useful"
                "Extremely useful"]}})
  
